/**
 * DO NOT EDIT THIS FILE, instead copy it to database.js and set
 * the database name to connect to.
 *
 * You can set any database name you want and the application will
 * create the database file automatically and initialize it.
 */

module.exports = {
  database: 'default',
};
